name: 'Contributing Check and Update'
description: 'Checks contributing file in calling repo and creates a PR if it''s outdated'

inputs:
  branch:
    description: 'The branch to get the template file from'
    required: false
    default: 'main'
  contributing_update_dir:
    description: 'The directory path for contributing update'
    required: false
    default: 'contributing_update_temp'

runs:
  using: 'composite'
  steps:
    - uses: 'actions/checkout@v3'
    - name: 'Make temporary dir for this job'
      shell: bash
      run: |
        mkdir -p "${{ inputs.contributing_update_dir }}"
    - name: 'Download template file'
      shell: bash
      run: |
        wget -O "${{ inputs.contributing_update_dir }}/contributing.md.template" "https://raw.githubusercontent.com/canonical/charmed-kubeflow-workflows/${{ inputs.branch }}/contributing_update/contributing.md.template"
    - name: 'Generate and compare'
      id: generate-and-compare
      shell: bash
      run: |
        bash ${{ github.action_path }}/generate_and_compare.sh "${{ inputs.contributing_update_dir }}"
