name: 'Contributing Check and Update'
description: 'Checks contributing file in calling repo and creates a PR if it''s outdated'

inputs:
  branch:
    description: 'The branch to get the template file from'
    required: false
    default: 'main'
  contributing_update_dir:
    description: 'The directory path for contributing update'
    required: false
    default: 'contributing_update_temp'

runs:
  using: 'composite'
  steps:
    - name: 'Install yq'
      shell: bash
      run: |
        # Download and install yq binary
        mkdir -p "${HOME}/bin"
        wget -q https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64 -O "${HOME}/bin/yq"
        chmod +x "${HOME}/bin/yq"
    - name: 'Set yq path in environment file'
      shell: bash
      run: echo "${HOME}/bin" >> $GITHUB_PATH
    - uses: 'actions/checkout@v3'
    - name: 'Make temporary dir for this job'
      shell: bash
      run: |
        mkdir -p "${{ inputs.contributing_update_dir }}"
    - name: 'Download template file'
      shell: bash
      run: |
        wget -O "${{ inputs.contributing_update_dir }}/contributing.md.template" "https://raw.githubusercontent.com/canonical/charmed-kubeflow-workflows/${{ inputs.branch }}/contributing_update/contributing.md.template"
    - name: 'Generate and compare'
      id: generate-and-compare
      shell: bash
      run: |
        bash ${{ github.action_path }}/generate_and_compare.sh "${{ inputs.contributing_update_dir }}"
