name: 'Contributing Check and Update'
description: Checks contributing file in calling repo and creates a PR if it's outdated

runs:
  using: 'composite'
  steps:
    - uses: 'actions/checkout@v3'
    - name: 'Generate and compare'
      id: generate-and-compare
      shell: bash
      run: bash ${{ github.action_path }}/generate_and_compare.sh  