# Meant to be copied over as is in all ROCKs repositories with
# the name `on_pull_request.yaml` after adjusting microk8s and 
# juju channels and uncommenting/remove python-version input.
# If rockcraft-channel is omitted, it will install from stable 
# by default
name: On Pull Request

on:
  pull_request:

jobs:

  on-pull-request:
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/get-rocks-modified-and-build-scan-test-publish.yaml@main
    permissions:
      pull-requests: read
    secrets: inherit
    with:
      # rockcraft-channel: latest/stable
      microk8s-channel: 1.32/stable
      juju-channel: 3.6/stable
      # python-version: "3.8"
