jobs:
  terraform-deploy:
    name: Deploy Terraform
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/terraform-deploy.yaml@main
    with:
      # Defaults to "testing"
      model: kubeflow
      # Defaults to "latest/stable" due to it being the default channel in most of our charms
      channel: latest/edge
      # Add the line below for multi-charm repos. For single-repo repositories, it can be 
      # omitted since the workflow was designed according to CC006 spec file structure conventions.
      working-directory: charms/<charm-name>/terraform
      # The following line is useful when there are no dependencies for a charm to go `active`. Otherwise,
      # setting it to true will cause the workflow to timeout if the unit never goes to `active`.
      workload-check: true
      
