# this CI is for internal import from another template
name: Quality Checks

on:
  workflow_call:
    inputs:
      charm-path:
        required: true
        type: string

jobs:
  lib-check:
    name: Check libraries
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@2.2.5
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          charm-path: "${{ inputs.charm-path }}"
          charmcraft-channel: 3.x/edge # TODO: remove after charmcraft 3.3 stable release

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: python3 -m pip install tox
      - run: tox -c ${{ inputs.charm-path }} -e lint
