# this CI is for internal import from another template
name: Unit and Integration Tests

on:
  workflow_call:
    inputs:
      charm-name:
        required: true
        type: string

jobs:
  unit:
    name: Unit tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: python3 -m pip install tox
      - run: tox -e ${{ inputs.charm-name }}-unit


  integration:
    name: Integration tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: 1.24/stable
          charmcraft-channel: latest/candidate
          # Pinning juju agent to 2.9.42 to keep compatibility with pythonlib-juju<3
          bootstrap-options: --agent-version="2.9.42"

      # TODO: Remove once the actions-operator does this automatically
      - name: Configure kubectl
        run: |
          sg microk8s -c "microk8s config > ~/.kube/config"

      - run: sg microk8s -c "microk8s enable metallb:'10.64.140.43-10.64.140.49,192.168.0.105-192.168.0.111'"
      - run: |
          sg microk8s -c "tox -e ${{ inputs.charm-name }}-integration"

      # Collect debug logs if failed
      - name: Dump Juju/k8s logs on failure
        uses: canonical/charm-logdump-action@main
        if: failure()
        with:
          app: ${{ inputs.charm-name }}
          model: testing
