# this CI is for internal import from another template
name: Unit Tests

on:
  workflow_call:
    inputs:
      charm-name:
        required: true
        type: string
      tox-uv:
        description: Whether to install `tox` via `uv` with its `tox-uv` plugin and to run it from `uv`'s environments. The alternative (when false) is simply installing `tox` via `pip` and running `tox` standalone.
        required: false
        type: boolean
        default: false

jobs:
  unit:
    name: Unit tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install tox
        uses: canonical/charmed-kubeflow-workflows/.github/actions/install-tox@feat/tox-uv-support
        with:
          tox-uv: ${{ inputs.tox-uv }}
      - run: tox -e ${{ inputs.charm-name }}-unit
