name: Build, scan, and test ROCK

on:
  workflow_call:
    inputs:
      rock-dir:
        description: "Path to rock directory, i.e. directory containing rockcraft.yaml"
        required: true
        type: string
      microk8s-channel:
        description: "Microk8s channel e.g. 1.26/stable"
        required: true
        default: "1.26/stable"
        type: string
      juju-channel:
        description: "Juju channel e.g. 3.1/stable"
        required: true
        default: "3.1/stable"
        type: string
      python-version:
        description: "Version of python to use for integration tests. If empty, it will use machine's default"
        default: ""
        required: false
        type: string
jobs:

  build:
    uses: ./.github/workflows/build-rock.yaml
    with:
      rock-dir: ${{ inputs.rock-dir }}

  publish:
    if: ${{ github.event_name == 'push' }}
    uses: ./.github/workflows/publish-rock.yaml
    secrets: inherit
    with:
      rock-artifact: "artifact"
      rock-reference: "rock"
      rock-filename: "rock"
      registry: "charmedkubeflow"
