name: Build and scan ROCK, save and send scan report

on:
  workflow_call:
    inputs:
      rock:
        description: "Path to rock directory, i.e. directory containing rockcraft.yaml"
        default: "."
        required: true
        type: string

jobs:
  build-scan-rock:
    runs-on: ubuntu-20.04
    name: Build and scan ROCK
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install tools
        run: |
          sudo snap install jq
          sudo snap install yq
      - name: Build ROCK
        uses: canonical/craft-actions/rockcraft-pack@main
        with:
          path: ${{ inputs.rock }}
      - name: Copy ROCK to Docker
        id: rock_in_docker
        run: |
          NAME=$(yq eval ".name" rockcraft.yaml)
          VERSION=$(yq eval ".version" rockcraft.yaml)
          ARCH=$(yq eval ".platforms | keys" rockcraft.yaml | awk -F ' ' '{print $2}')
          ROCK="${NAME}_${VERSION}_${ARCH}"
          sudo skopeo --insecure-policy copy oci-archive:$ROCK.rock docker-daemon:$ROCK:$VERSION
          echo "image=$ROCK:$VERSION" >> "$GITHUB_OUTPUT"
        working-directory: ${{ inputs.rock }}
      - name: Scan for vulnerabilities
        id: scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: '${{ steps.rock_in_docker.output.image }}'
          format: 'json'
          output: 'trivy-report-${{ inputs.rock }}.json'
          ignore-unfixed: true
        #working-directory: ${{ inputs.rock }}
      # - name: Send vulnerability records
      #   run: |
      #     ../tools/send-scan.sh ./trivy-reports ${{ secrets.JIRA_URL }}
      #   working-directory: ${{ inputs.rock }}
      - name: Prepare artifacts
        run: |
          tar zcvf trivy-report-${{ inputs.rock }}.tar.gz ./trivy-reports
        working-directory: ${{ inputs.rock }}
      # - name: Upload Trivy reports
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: trivy-report-${{ inputs.rock }}
      #     path: trivy-report-${{ inputs.rock }}.${{ strategy.job-index }}.tar.gz

