name: 'Build and publish rock'
on:
  workflow_call:
    inputs:
      rock-dir:
        description: "Path to rock directory, i.e. directory containing rockcraft.yaml"
        required: true
        default: '.'
        type: string
      source-branch:
        description: Github branch from this repo to publish.  If blank, will use the default branch
        default: ''
        required: false
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build:
    name: Build ${{ inputs.rock-dir }}
    uses: ./.github/workflows/build-rock.yaml
    with:
      rock-dir: ${{ inputs.rock-dir }}
      source-branch: ${{ inputs.source-branch }}

  publish:
    needs: [build]
    uses: ./.github/workflows/publish-rock.yaml
    secrets: inherit
    with:
      rock-dir: ${{ inputs.rock-dir }}
      path-to-rock-file: ${{ needs.build.outputs.path-to-rock-file }}
