name: Build, scan, and test ROCK

on:
  workflow_call:
    inputs:
      rock-dir:
        description: "Path to rock directory, i.e. directory containing rockcraft.yaml"
        required: true
        type: string
      microk8s-channel:
        description: "Microk8s channel e.g. 1.26/stable"
        required: true
        default: "1.26/stable"
        type: string
      juju-channel:
        description: "Juju channel e.g. 3.1/stable"
        required: true
        default: "3.1/stable"
        type: string
      python-version:
        description: "Version of python to use for integration tests. If empty, it will use machine's default"
        default: ""
        required: false
        type: string
jobs:

  build:
    uses: ./.github/workflows/build-rock.yaml
    with:
      rock-dir: ${{ inputs.rock-dir }}

  scan:
    needs: build
    uses: ./.github/workflows/scan-rock.yaml
    secrets: inherit
    with:
      rock-artifact: ${{ needs.build.outputs.rock-artifact}}
      rock-reference: ${{ needs.build.outputs.rock-reference }}
      rock-filename: ${{ needs.build.outputs.rock-filename }}

  sanity-tests:
    needs: build
    uses: ./.github/workflows/sanity-test-rock.yaml
    with:
      tests-dir: ${{ inputs.rock-dir }}
      rock-artifact: ${{ needs.build.outputs.rock-artifact}}
      rock-reference: ${{ needs.build.outputs.rock-reference }}
      rock-filename: ${{ needs.build.outputs.rock-filename }}

  integration-tests:
    needs: build
    uses: ./.github/workflows/integration-test-rock.yaml
    with:
      tests-dir: ${{ inputs.rock-dir }}
      rock-artifact: ${{ needs.build.outputs.rock-artifact}}
      rock-reference: ${{ needs.build.outputs.rock-reference }}
      rock-filename: ${{ needs.build.outputs.rock-filename }}
      microk8s-channel: ${{ inputs.microk8s-channel }}
      juju-channel: ${{ inputs.juju-channel }}
      python-version: ${{ inputs.python-version }}

  publish:
    if: ${{ github.event_name == 'push' }}
    needs: [scan, build, sanity-tests, integration-tests]
    uses: ./.github/workflows/publish-rock.yaml
    secrets: inherit
    with:
      rock-artifact: ${{ needs.build.outputs.rock-artifact}}
      rock-reference: ${{ needs.build.outputs.rock-reference }}
      rock-filename: ${{ needs.build.outputs.rock-filename }}
      registry: "charmedkubeflow"
