name: Build, scan, and test ROCK

on:
  workflow_call:
    inputs:
      rock-dir:
        description: "Path to rock directory, i.e. directory containing rockcraft.yaml"
        required: true
        type: string
      microk8s-channel:
        description: "Microk8s channel e.g. 1.26/stable"
        required: true
        default: "1.26/stable"
        type: string
      juju-channel:
        description: "Juju channel e.g. 3.1/stable"
        required: true
        default: "3.1/stable"
        type: string
      publish:
        description: "Define if workflow should also publish the charm"
        default: false
        type: boolean

jobs:

  build:
    name: Build ${{ inputs.rock-dir }}
    uses: ./.github/workflows/build-rock.yaml
    with:
      rock-dir: ${{ inputs.rock-dir }}

  scan:
    needs: build
    uses: ./.github/workflows/scan-rock.yaml
    with:
      rock-dir: ${{ inputs.rock-dir }}
      path-to-rock-file: ${{ needs.build.outputs.path-to-rock-file }}

  integration-tests:
    needs: build
    uses: ./.github/workflows/test-rock.yaml
    with:
      rock-dir: ${{ inputs.rock-dir }}
      path-to-rock-file: ${{ needs.build.outputs.path-to-rock-file }}
      microk8s-channel: ${{ inputs.microk8s-channel }}
      juju-channel: ${{ inputs.juju-channel }}

  publish:
    if: ${{ inputs.publish }} == true
    needs: [scan, build, integration-tests]
    uses: ./.github/workflows/publish-rock.yaml
    secrets: inherit
    with:
      rock-dir: ${{ inputs.rock-dir }}
      path-to-rock-file: ${{ needs.build.outputs.path-to-rock-file }}
