name: Build, scan, and test rock

on:
  workflow_call:
    inputs:
      rock-dir:
        description: "Path to rock directory, i.e. directory containing rockcraft.yaml"
        required: true
        type: string
      rockcraft-channel:
        description: "Rockcraft channel e.g. latest/stable"
        required: false
        default: "latest/stable"
        type: string
      microk8s-channel:
        description: "Microk8s channel e.g. 1.32/stable"
        required: false
        default: "1.32/stable"
        type: string
      juju-channel:
        description: "Juju channel e.g. 3.6/stable"
        required: false
        default: "3.6/stable"
        type: string
      python-version:
        description: "Version of python to use for integration tests. If empty, it will use machine's default"
        default: ""
        required: false
        type: string
      base-ref:
        description: "Branch, tag, or commit SHA to checkout, build, test and publish. If empty, the workflow's default ref is used."
        required: false
        default: ''
        type: string

jobs:

  resolve-image-tag:
    uses: ./.github/workflows/resolve-image-tag.yaml
    with:
      rock-dir: ${{ inputs.rock-dir }}
      base-ref: ${{ inputs.base-ref }}

  build:
    needs: [resolve-image-tag]
    uses: ./.github/workflows/build-rock.yaml
    with:
      rock-dir: ${{ inputs.rock-dir }}
      rockcraft-channel: ${{ inputs.rockcraft-channel }}
      rockcraft-extra-args: ${{ needs.resolve-image-tag.outputs.base == 'ubuntu@20.04' && '--ignore=unmaintained' || '' }}
      source-branch: ${{ inputs.base-ref }}

  scan:
    needs: [build, resolve-image-tag]
    uses: ./.github/workflows/scan-rock.yaml
    secrets: inherit
    with:
      rock-artifact: ${{ needs.build.outputs.rock-artifact }}
      rock-reference: ${{ needs.resolve-image-tag.outputs.rock-reference }}
      rock-filename: ${{ needs.build.outputs.rock-filename }}
      rockcraft-channel: ${{ inputs.rockcraft-channel }}

  sanity-tests:
    needs: [build, resolve-image-tag]
    uses: ./.github/workflows/sanity-test-rock.yaml
    with:
      tests-dir: ${{ inputs.rock-dir }}
      rock-artifact: ${{ needs.build.outputs.rock-artifact }}
      rock-reference: ${{ needs.resolve-image-tag.outputs.rock-reference }}
      rock-filename: ${{ needs.build.outputs.rock-filename }}
      rockcraft-channel: ${{ inputs.rockcraft-channel }}
      source-branch: ${{ inputs.base-ref }}

  integration-tests:
    needs: [build, resolve-image-tag]
    uses: ./.github/workflows/integration-test-rock.yaml
    with:
      tests-dir: ${{ inputs.rock-dir }}
      rock-artifact: ${{ needs.build.outputs.rock-artifact }}
      rock-reference: ${{ needs.resolve-image-tag.outputs.rock-reference }}
      rock-filename: ${{ needs.build.outputs.rock-filename }}
      python-version: ${{ inputs.python-version }}
      source-branch: ${{ inputs.base-ref }}

  publish:
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
    needs: [scan, build, sanity-tests, integration-tests, resolve-image-tag]
    uses: ./.github/workflows/publish-rock.yaml
    secrets: inherit
    with:
      rock-artifact: ${{ needs.build.outputs.rock-artifact }}
      rock-filename: ${{ needs.build.outputs.rock-filename }}
      full-image-tag: ${{ needs.resolve-image-tag.outputs.full-image-tag }}
      rockcraft-channel: ${{ inputs.rockcraft-channel }}
      source-branch: ${{ inputs.base-ref }}

  integrate-on-pr:
    if: ${{ github.event_name == 'pull_request' }}
    needs: [resolve-image-tag]
    uses: ./.github/workflows/integrate-rock.yaml
    with:
      rock-dir: ${{ inputs.rock-dir }}
      event-name: ${{ github.event_name }}
      full-image-tag: ${{ needs.resolve-image-tag.outputs.full-image-tag }}
    secrets: inherit

  integrate-on-merge:
    if: ${{ github.event_name == 'push' }}
    needs: [publish, resolve-image-tag]
    uses: ./.github/workflows/integrate-rock.yaml
    with:
      rock-dir: ${{ inputs.rock-dir }}
      event-name: ${{ github.event_name }}
      full-image-tag: ${{ needs.resolve-image-tag.outputs.full-image-tag }}
      base-ref: ${{ inputs.base-ref }}
    secrets: inherit

  integrate-on-dispatch:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
    needs: [publish, resolve-image-tag]
    uses: ./.github/workflows/integrate-rock.yaml
    with:
      rock-dir: ${{ inputs.rock-dir }}
      event-name: ${{ github.event_name }}
      full-image-tag: ${{ needs.resolve-image-tag.outputs.full-image-tag }}
      base-ref: ${{ inputs.base-ref }}
    secrets: inherit
