#Updates contributing files for all charms in calling repo as necessary, creating a PR for any that are outdated
name: 'Update all Contributing Files'

on:
  workflow_call:
    inputs:
      branch:
        description: 'The branch to get the contributing template file from'
        required: false
        default: 'main'
        type: 'string'
      charm-paths-action-branch:
        description: 'The branch to use for the get-charm-paths action'
        required: false
        default: 'main'
        type: 'string'
    outputs:
      charm_paths:
        description: 'Charm paths'
        value: ${{ jobs.get-charm-paths.outputs.charm-paths }}

jobs:
  get-charm-paths:
    name: Generate the Charm Matrix content
    runs-on: ubuntu-latest
    outputs:
      charm_paths: ${{ steps.get-charm-paths.outputs.charm-paths }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get paths for all charms in this repo
        id: get-charm-paths        
        uses: canonical/kubeflow-ci/actions/get-charm-paths@add-get-charm-paths #${{ inputs.charm-paths-action-branch }}

  echo-charm-paths:
    name: Echo charm paths emitted
    runs-on: ubuntu-latest
    needs: get-charm-paths
    steps:
      - run: echo "Hello World" #"Got charm_paths: ${{ needs.get-charm-paths.outputs.charm_paths }}"

  use-charm-paths:
    name: Use charm paths in a matrix
    runs-on: ubuntu-latest
    needs: get-charm-paths
    strategy:
      fail-fast: false
      matrix:
        charm-path: ${{ fromJson(needs.get-charm-paths.outputs.charm_paths) }}
    steps:
      - run: echo "Hello World" #"Got charm path: ${{ matrix.charm-path }}"