name: Integrate ROCK into charm

on:
  workflow_call:
    inputs:
      rock-dir:
        required: true
        type: string
      event-name:
        required: true
        type: string
      published-image:
        description: "Full image reference published to registry (used for merged PRs)"
        required: false
        type: string
      rock-reference:
        description: "Rock reference in <name>:<version> form (used in PRs)"
        required: false
        type: string
      registry:
        description: "Docker registry base (used in PRs)"
        required: false
        default: "docker.io/charmedkubeflow"
        type: string

  workflow_dispatch:
    inputs:
      rock-dir:
        description: "Path to the rock directory (e.g. rocks/my-rock)"
        required: true
        type: string
      target-branch:
        description: "Branch to integrate into"
        required: true
        type: string
      dry-run:
        description: "Run in dry-run mode?"
        required: false
        default: true
        type: boolean
      published-image:
        description: "Full image reference from Docker registry"
        required: false
        type: string
      rock-reference:
        description: "Rock reference (e.g. api-server:2.5.0)"
        required: false
        type: string
      registry:
        description: "Docker registry base (e.g. docker.io/charmedkubeflow)"
        required: false
        type: string
        default: "docker.io/charmedkubeflow"

jobs:
  integrate-rock:
    runs-on: ubuntu-24.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install charmed-analytics-ci
        run: pip install charmed-analytics-ci

      - name: Install yq
        run: sudo snap install yq

      - name: Determine image tag
        id: tag
        run: |
          if [[ -n "${{ inputs.published-image }}" ]]; then
            echo "Using published image: ${{ inputs.published-image }}"
            echo "final_tag=${{ inputs.published-image }}" >> $GITHUB_OUTPUT
          elif [[ -n "${{ inputs.rock-reference }}" ]]; then
            echo "Constructing image tag from rock-reference and registry"
            COMMIT_ID=$(git rev-parse --short HEAD)
            FINAL_TAG="${{ inputs.registry }}/${{ inputs.rock-reference }}-${COMMIT_ID}"
            echo "Generated image tag: $FINAL_TAG"
            echo "final_tag=$FINAL_TAG" >> $GITHUB_OUTPUT
          else
            echo "❌ Error: Neither 'published-image' nor 'rock-reference' provided"
            exit 1
          fi

      - name: Determine target branch and dry-run
        id: params
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "target_branch=${{ inputs.target-branch }}" >> $GITHUB_OUTPUT
            if [[ "${{ inputs.dry-run }}" == "true" ]]; then
              echo "dry_run=--dry-run" >> $GITHUB_OUTPUT
            else
              echo "dry_run=" >> $GITHUB_OUTPUT
            fi
          else
            if [[ "${{ inputs.event-name }}" == "pull_request" ]]; then
              echo "target_branch=main" >> $GITHUB_OUTPUT
              echo "dry_run=--dry-run" >> $GITHUB_OUTPUT
            else
              echo "target_branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
              echo "dry_run=" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Determine triggering PR (if merged)
        id: triggering_pr
        run: |
          if [[ "${{ inputs.event-name }}" != "pull_request" ]]; then
            sudo apt update && sudo apt install -y gh

            pr_number=$(gh pr list --state merged --search "$(git rev-parse --short HEAD)" --json number --jq '.[0].number' || true)

            if [[ -n "$pr_number" ]]; then
              pr_url="https://github.com/${{ github.repository }}/pull/$pr_number"
              echo "Found triggering PR: $pr_url"
              echo "url=$pr_url" >> "$GITHUB_OUTPUT"
            else
              echo "No triggering PR found."
              echo "url=" >> "$GITHUB_OUTPUT"
            fi
          else
            echo "PR event — skipping triggering PR detection."
            echo "url=" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chaci integrate-rock
        run: |
          chaci integrate-rock \
            "${{ inputs.rock-dir }}/rock-ci-metadata.yaml" \
            "${{ steps.params.outputs.target_branch }}" \
            "${{ steps.tag.outputs.final_tag }}" \
            ${{ steps.params.outputs.dry_run }} \
            $([[ -n "${{ steps.triggering_pr.outputs.url }}" ]] && echo "--triggering-pr ${{ steps.triggering_pr.outputs.url }}")
