name: Publish ROCK

on:
  workflow_call:
    inputs:
      rock-dir:
        description: "Path to rock directory, i.e. directory containing rockcraft.yaml"
        required: true
        type: string
      rock-filename:
        description: "Filename of .rock file produced"
        required: true
        type: string
jobs:

  publish-rock:
    name: Publish ${{ inputs.rock-dir }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.rock-dir }}
          path: ${{ inputs.rock-dir }}/

      - name: Copy rock and publish to Dockerhub
        id: rock_in_docker
        run: |
          NAME=$(yq eval ".name" rockcraft.yaml)
          VERSION=$(yq eval ".version" rockcraft.yaml)
          COMMIT_ID=$(git rev-parse --short HEAD)
          sudo skopeo --insecure-policy copy oci-archive:${{ inputs.rock-filename}} docker-daemon:charmedkubeflow/$NAME:$VERSION
          docker tag charmedkubeflow/$NAME:$VERSION charmedkubeflow/$NAME:${VERSION}-${COMMIT_ID}
          docker push charmedkubeflow/$NAME:${VERSION}-${COMMIT_ID}
        working-directory: ${{ inputs.rock-dir }}
