name: Pull Request

on:
  workflow_call:
    inputs:
      charm-path:
        description: "Path to the charm we want to test/publish. Defaults to the current working directory."
        default: '.'
        required: false
        type: string

      charm-name:
        required: true
        type: string


jobs:
  quality-checks:
    name: Quality Checks
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_quality-checks.yaml@all
    with:
      charm-path: ${{ inputs.charm-path }}
      charm-name: ${{ inputs.charm-name }}

  tests:
    name: Tests
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_tests.yaml@all
    with:
      charm-name: ${{ inputs.charm-name }}
