name: Pull Request

on:
  workflow_call:
    inputs:
      charm-path:
        description: "Path to the charm we want to test/publish. Defaults to the current working directory."
        default: '.'
        required: false
        type: string

      charm-name:
        required: true
        type: string

      run-bundle:
        description: "Run the bundle test"
        default: false
        required: false
        type: boolean

      run-observability:
        description: "Run the observability test"
        default: false
        required: false
        type: boolean

      publish:
        description: "Publish the charm"
        default: true
        required: false
        type: boolean

    secrets:
       CHARMCRAFT_CREDENTIALS:
         required: false
jobs:
  quality-checks:
    name: Quality Checks
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_quality-checks.yaml@all

  tests:
    name: Tests
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_tests.yaml@all
    with:
      charm-path: ${{ inputs.charm-path }}

  bundle:
    name: Bundle
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_bundle.yaml@all
    if: ${{ inputs.run-bundle }}
    with:
        charm-path: ${{ inputs.charm-name }}

  observability:
    name: Observability
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_observability.yaml@all
    if: ${{ inputs.run-observability }}
    with:
      charm-path: ${{ inputs.charm-name }}

  publish:
    name: Publish
    needs: tests
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/_publish.yaml@all
    if: ${{ inputs.publish }}
