name: Integration tests

on:
  workflow_call:
    inputs:
      tests-dir:
        description: "Path to tests directory"
        required: true
        type: string
      rock-filename:
        description: "Filename of the .rock file to be tested"
        required: true
        type: string
      rock-name:
        description: "Field name of the rockcraft.yaml file to be tested"
        required: true
        type: string
      rock-version:
        description: "Field version of the rockcraft.yaml file to be tested"
        required: true
        type: string
      source-branch:
        description: Github branch to checkout. If blank, it will use default values.
        default: '' # For default behaviour, see https://github.com/actions/checkout/tree/v4/#usage
        required: false
        type: string
jobs:
  tests:
    name: Sanity test ${{ inputs.rock-filename }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.source-branch }}

      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.rock-filename }}

      - name: Export ROCK to Docker
        id: rock_in_docker
        run: |
          DOCKER_IMAGE=${{ inputs.rock-name }}:${{ inputs.rock-version }}
          sudo skopeo --insecure-policy copy oci-archive:${{ inputs.rock-filename }} docker-daemon:$DOCKER_IMAGE
          echo "image=$DOCKER_IMAGE" >> "$GITHUB_OUTPUT"

      - name: Sanity tests
        run: |
          tox -e sanity
        working-directory: ./${{ inputs.tests-dir }}
