# reusable workflow triggered by other actions
name: Terraform checks for solution modules

on:
  workflow_call:
    inputs:
      module-path:
        description: The path to the Terraform solution module.
        required: true
        type: string
jobs:

  check:
    name: Check
    uses: canonical/sdcore-github-workflows/.github/workflows/terraform.yaml@v1.0.0
    with:
      working-directory: ${{ inputs.module-path }}

  lint:
    name: Lint
    uses: ./.github/workflows/terraform-lint.yaml
    with:
      module-path: ${{ inputs.module-path }}


