name: Lint Terraform module

on:
  workflow_call:
    inputs:
      module-path:
        description: The path to the Terraform module. Requires a `tflint` tox environment to be present there.
        required: true
        type: string
      tox-uv:
        description: Whether to install `tox` via `uv` with its `tox-uv` plugin and to run it from `uv`'s environments. The alternative (when false) is simply installing `tox` via `pip` and running `tox` standalone.
        required: false
        type: boolean
        default: false

jobs:
  lint:
    name: Lint Terraform
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
      - uses: canonical/charmed-kubeflow-workflows/.github/actions/install-tox@feat/tox-uv-support
        with:
          tox-uv: ${{ inputs.tox-uv }}
      - run: tox -c ${{ inputs.module-path }} -e tflint
