# reusable workflow triggered by other actions
name: Terraform checks for charm modules

on:
  workflow_call:
    inputs:
      charm-path:
        required: true
        type: string
      model:
        description: The model that the charm is deployed on. Defaults to `tf-testing`.
        required: false
        type: string
        default: tf-testing
      channel:
        description: The channel that the charm is deployed from. If not provided, no channel is specified and it uses the default value in the terraform module (which may depend on the specific TF module commit/branch).
        required: false
        type: string
      apply:
        description: Boolean value that defines if `apply` job runs. Defaults to `true`.
        required: false
        type: boolean
        default: true
jobs:
  apply:
    name: Apply
    uses: ./.github/workflows/terraform-apply.yaml
    if: ${{ inputs.apply }}
    with:
      model: ${{ inputs.model }}
      channel: ${{ inputs.channel }}
      module-directory: ${{ inputs.charm-path }}/terraform

  check:
    name: Check
    uses: canonical/sdcore-github-workflows/.github/workflows/terraform.yaml@v1.0.0
    with:
      working-directory: ${{ inputs.charm-path }}/terraform

  lint:
    name: Lint
    uses: ./.github/workflows/terraform-lint.yaml
    with:
      module-path: ${{ inputs.charm-path }}