# reusable workflow triggered by other actions
name: Terraform checks for solution modules

on:
  workflow_call:
    inputs:
      module-path:
        description: The path to the Terraform solution module.
        required: true
        type: string
      tox-uv:
        description: Whether to install `tox` via `uv` with its `tox-uv` plugin and to run it from `uv`'s environments. The alternative (when false) is simply installing `tox` via `pip` and running `tox` standalone.
        required: false
        type: boolean
        default: false

jobs:

  check:
    name: Check
    uses: canonical/sdcore-github-workflows/.github/workflows/terraform.yaml@v1.0.0
    with:
      working-directory: ${{ inputs.module-path }}

  lint:
    name: Lint
    uses: ./.github/workflows/terraform-lint.yaml
    with:
      module-path: ${{ inputs.module-path }}
      tox-uv: ${{ inputs.tox-uv }}


