# reusable workflow triggered by other actions
name: Terraform checks for charm modules

on:
  workflow_call:
    inputs:
      charm-path:
        required: true
        type: string
      model:
        description: The model that the charm is deployed on. Defaults to `testing`.
        required: false
        type: string
        default: tf-testing
      channel:
        description: The channel that the charm is deployed from. Defaults to `latest/edge`.
        required: false
        type: string
        default: latest/edge
      apply:
        description: Boolean value that defines if `apply` job runs. Defaults to `true`.
        required: false
        type: boolean
        default: true
jobs:
  apply:
    name: Apply
    uses: ./.github/workflows/terraform-apply.yaml
    if: ${{ inputs.apply }}
    with:
      model: ${{ inputs.model }}
      channel: ${{ inputs.channel }}
      module-directory: ${{ inputs.charm-path }}/terraform

  check:
    name: Check
    uses: canonical/sdcore-github-workflows/.github/workflows/terraform.yaml@v1.0.0
    with:
      working-directory: ${{ inputs.charm-path }}/terraform

  lint:
    name: Lint
    uses: ./.github/workflows/terraform-lint.yaml
    with:
      module-path: ${{ inputs.charm-path }}
