# reusable workflow for checking library versions and opening 
# PRs to bump outdated ones
name: Update Charm Libraries

on:
  workflow_call:
    inputs:
      charmcraft_channel:
        description: Channel from which to install charmcraft
        default: 'latest/candidate'
        required: false
        type: string
    secrets:
      CHARMCRAFT_CREDENTIALS:
        required: true
      PAT:
        required: true
        description: "Github PAT that can create pull requests for the repo being bumped.  If this is a default GITHUB_TOKEN, the PRs generated will not trigger push/pull_request CI workflows"
  workflow_dispatch:
    inputs:
      charmcraft_channel:
        description: Channel from which to install charmcraft
        default: 'latest/candidate'
        required: false
        type: string

jobs:
  get-charm-paths:
    name: Get paths to all charms in repo
    runs-on: ubuntu-latest
    outputs:
      charm-paths: ${{ steps.get-charm-paths.outputs.charm-paths }}
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: Get paths for all charms in this repo
        id: get-charm-paths
        # TODO: Pin this to a central, released version
        uses: ca-scribner/github-actions-recipes/get-charm-paths-python@master

  update-libs:
    name: Update charm libraries
    runs-on: ubuntu-latest
    needs: get-charm-paths
    strategy:
      fail-fast: false
      matrix:
        charm-path: ${{ fromJson(needs.get-charm-paths.outputs.charm-paths) }}
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - run: sudo snap install charmcraft --channel ${{ inputs.charmcraft_channel }} --classic
      - name: update charm libs
        env:
          CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
        working-directory: ${{ matrix.charm-path }}
        run: charmcraft fetch-lib
      # TODO: This does not work here because the charming-action revert's its own changes after checking.  
      #       This is done [here](https://github.com/canonical/charming-actions/blob/45b5fb810fe761aa4120e79d134f9bd8d87f4f51/src/actions/check-libraries/check-libraries.ts#L70).  
      #       If we made that configurable (boolean input option that lets us skip it), it should
      #       work for us here (but not sure where the messages get written to, so maybe not worthwhile)
      # - name: Check libraries
      #   uses: canonical/charming-actions/check-libraries@1.0.3
      #   with:
      #     credentials: "${{ secrets.CHARMCRAFT_CREDENTIALS }}"
      #     github-token: "${{ secrets.GITHUB_TOKEN }}"
      #     charm-path: "${{ matrix.charm-path }}"
      # Assembles inputs and applies defaults before creating PR
      - name: Compile PR inputs
        id: compile-inputs
        run: |
          # charm name and branch suffix
          # if charm_path = ./ --> charm_name='', branch_suffix='' (null)
          # if charm_path != ./ (eg: a charm in a ./charms dir) --> tag_prefix = 'some-charm'
          if [ ${{ matrix.charm-path }} == './' ]; then
            CHARM_NAME=""
            BRANCH_SUFFIX=""
            PR_MESSAGE_SUFFIX=""
          else
            CHARM_NAME="$(basename ${{ matrix.charm-path }} )"
            BRANCH_SUFFIX="-$CHARM_NAME"
            PR_MESSAGE_SUFFIX=" ($CHARM_NAME)"
          fi
          echo "setting output of charm-name=$CHARM_NAME"
          echo "::set-output name=charm-name::$CHARM_NAME"

          echo "setting output of branch-suffix=$BRANCH_SUFFIX"
          echo "::set-output name=branch-suffix::$BRANCH_SUFFIX"

          echo "setting output of pr_message-suffix=$PR_MESSAGE_SUFFIX"
          echo "::set-output name=pr_message-suffix::$PR_MESSAGE_SUFFIX"

      - name: Create Pull Request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "(Automated) Update Charm Libs${{ steps.compile-inputs.outputs.pr_message-suffix}}"
          body: "Update charm libs${{ steps.compile-inputs.outputs.pr_message-suffix}}"
          commit-message: "Update charm libs${{ steps.compile-inputs.outputs.pr_message-suffix}}"
          signoff: false
          delete-branch: true
          branch: "automated-update-charm-libs${{ steps.compile-inputs.outputs.branch-suffix }}"
          token: "${{ secrets.PAT }}"

      - name: Print Created Pull Request
        if: ${{ steps.create-pull-request.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
